color_detector:
  ros__parameters:
    min_area: 300

    hsv_ranges:
      RED1:
        low:  [  0,100,100]
        high: [ 10,255,255]
      RED2:
        low:  [160,100,100]
        high: [180,255,255]
      YELLOW:
        low:  [ 18,100,100]
        high: [ 30,255,255]
      GREEN:
        low:  [ 40, 40, 40]
        high: [ 80,255,255]