path_generator:
  ros__parameters:
    #points stored as a flat list of doubles.
    # For each point: [x, y]
    #path_points: [0.0, 2.0, 2.0, 2.0, 2.0, 0.0, 0.0, 0.0] #square
    path_points: [1.0, 0.0, 1.5, 0.5, 1.5, -0.5, 1.0, 0.0] #cocktail glass normal
    #path_points: [1.5, 0.5, 1.5, -0.5, 0.0, 0.0, 1.0, 0.0] #cocktail glass alternate

    #path_points: [0.5, 0.0] # Error validation

path_control:
  ros__parameters:
    #Controller Gains
    kp_v: 0.2 #Linear velocity gain
    kp_w: 1.1 #Angular velocity gain
    #Tolerance Threshold
    goal_threshold: 0.02 
    #Maximum velocities
    max_v: 0.5 #Max velocity
    max_w: 0.6 #Max angular velocity
