path_generator:
  ros__parameters:
    #points stored as a flat list of doubles.
    # For each point: [x, y]
    #path_points: [1.2,0.0,1.2,1.2,0.0,1.2,0.0,0.0] #square
    #path_points: [1.0, 0.0, 1.5, 0.5, 1.5, -0.5, 1.0, 0.0] #cocktail glass normal
    #path_points: [1.5, 0.5, 1.5, -0.5, 0.0, 0.0, 1.0, 0.0] #cocktail glass alternate
    #path_points: [1.2, -1.2, 2.4, -0.6, 1.2, 0.0, 0.0, 0.0] #Hook
    #path_points: [1.8, 0.0, 3.0, -0.6, 4.2, -0.6, 4.8, 0.0] #Sickle (Circle X2)
    #path_points: [1.2, 0.0, 2.4, -0.6, 3.6, -1.2, 4.8, -0.6] # Sickle (Triangle 3A)
    path_points: [1.2, 0.0, 3.6, -0.6, 4.8, -1.2, 6.0, -0.6] # Sickle (Triangle 3A)
    #path_points: [4.8, 0.0] # Speed Validation (Yellow - Green)
path_control:
  ros__parameters:
    #Controller Gains
    kp_v: 0.2 #Linear velocity gain
    kd_v: 0.1 #Linear velocity damping

    kp_w: 0.7 #Angular velocity gain
    ki_w: 0.0 #Angular velocity integral
    kd_w: 0.1 #Angular velocity damping

    #Tolerance Threshold
    goal_threshold: 0.01
    #Maximum velocities
    max_v: 0.3 #Max velocity
    max_w: 0.3 #Max angular velocity
